### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by paul-hammant** [hristo-vrigazov/bromium#66]
Change "Selenium does not include any synchronization logic, which makes tests unstable if one does not write a reliable one of his own." 

To: "Selenium does not include any synchronization logic, which makes tests flaky unless you implement wait-for logic to cater for timing differences"

Also, "synchronization" isnt the word usually used to describe timing problems between tests and the system they are testing.

**Comment by hristo-vrigazov** [comment]
Thank you for the suggestion! The sentence could be a bit unclear, especially the implicit reference "a reliable one of his own". About synchronization, why do you think it is inappropriate? What would you replace with? Because Bromium uses the classic Producer-Consumer problem to solve the "synchronization" problem, and to me it makes sense to call it like this.

**Comment by paul-hammant** [comment]
As you wish.
